FROM python:3.12-alpine

RUN apk add --no-cache tini

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py ./

EXPOSE 9200

ENTRYPOINT ["tini", "--"]
CMD ["python", "-u", "app.py"]
